### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider

### ISSUE THREAD

**Issue by zygimantus** [sir-ragna/noprint#1]
How you solved this error?:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at org.apache.pdfbox.pdmodel.PDDocument.protect(PDDocument.java:1318)
---
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

**Comment by sir-ragna** [comment]
@zygimantus did you add the Apache PDFBOX dependency in your project? https://pdfbox.apache.org/download.cgi

**Comment by sir-ragna** [comment]
This project is just a demo on how you could use the Apache Pdfbox library. I used it once to demonstrate a colleague on how he could use this library. (Note: I use the old pdfbox-app-1.8.7.jar version.)

You probably just want to look at the Pdfbox library and their documentation on how to use it.
https://pdfbox.apache.org/index.html

**Comment by zygimantus** [comment]
Yes. I added. But the problem was solved when I also added this dependency:
```
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.55</version>
        </dependency>
```

**Comment by hussienalbared** [comment]
I have faced the same problem, I was using bouncycastle as a dependency inside my project 1 then I have packaged project1 as a jar and added it as a dependency inside project 2.so it was not visible inside the project 2.
Solution
I added the same bouncycastle dependency inside project 2 and It worked.
 <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.68</version>
        </dependency>
